-- V2: Semantic search support.
-- Enables pgvector and adds a column to store a 384-dim embedding
-- (all-MiniLM-L6-v2 output size) per food, generated by the
-- nutrisight-ml FastAPI service from the food's name/category text.

CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE foods
    ADD COLUMN description_embedding vector(384);

-- HNSW index for fast approximate nearest-neighbor search once the
-- table has a meaningful number of embedded rows. Cosine distance is
-- used because sentence-transformer embeddings are compared by angle,
-- not magnitude.
CREATE INDEX idx_foods_description_embedding
    ON foods
    USING hnsw (description_embedding vector_cosine_ops);
